package models;
// Generated 03-feb-2017 13:15:08 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Flota generated by hbm2java
 */
public class Flota implements java.io.Serializable {

	private Integer idFlota;
	private int totalVehiculos;
	private int vehiculosActuales;
	private Set vehiculoses = new HashSet(0);

	public Flota() {
	}

	public Flota(int totalVehiculos, int vehiculosActuales) {
		this.totalVehiculos = totalVehiculos;
		this.vehiculosActuales = vehiculosActuales;
	}

	public Flota(int totalVehiculos, int vehiculosActuales, Set vehiculoses) {
		this.totalVehiculos = totalVehiculos;
		this.vehiculosActuales = vehiculosActuales;
		this.vehiculoses = vehiculoses;
	}

	public Integer getIdFlota() {
		return this.idFlota;
	}

	public void setIdFlota(Integer idFlota) {
		this.idFlota = idFlota;
	}

	public int getTotalVehiculos() {
		return this.totalVehiculos;
	}

	public void setTotalVehiculos(int totalVehiculos) {
		this.totalVehiculos = totalVehiculos;
	}

	public int getVehiculosActuales() {
		return this.vehiculosActuales;
	}

	public void setVehiculosActuales(int vehiculosActuales) {
		this.vehiculosActuales = vehiculosActuales;
	}

	public Set getVehiculoses() {
		return this.vehiculoses;
	}

	public void setVehiculoses(Set vehiculoses) {
		this.vehiculoses = vehiculoses;
	}

}
