package models;
// Generated 24-ene-2017 13:48:46 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta implements java.io.Serializable {

	private Integer idRuta;
	private int distanciaRuta;
	private byte[] coordenadasRuta;
	private Set registroRutas = new HashSet(0);

	public Ruta() {
	}

	public Ruta(int distanciaRuta) {
		this.distanciaRuta = distanciaRuta;
	}

	public Ruta(int distanciaRuta, byte[] coordenadasRuta, Set registroRutas) {
		this.distanciaRuta = distanciaRuta;
		this.coordenadasRuta = coordenadasRuta;
		this.registroRutas = registroRutas;
	}

	public Integer getIdRuta() {
		return this.idRuta;
	}

	public void setIdRuta(Integer idRuta) {
		this.idRuta = idRuta;
	}

	public int getDistanciaRuta() {
		return this.distanciaRuta;
	}

	public void setDistanciaRuta(int distanciaRuta) {
		this.distanciaRuta = distanciaRuta;
	}

	public byte[] getCoordenadasRuta() {
		return this.coordenadasRuta;
	}

	public void setCoordenadasRuta(byte[] coordenadasRuta) {
		this.coordenadasRuta = coordenadasRuta;
	}

	public Set getRegistroRutas() {
		return this.registroRutas;
	}

	public void setRegistroRutas(Set registroRutas) {
		this.registroRutas = registroRutas;
	}

}
